### ISSUE TITLE
Integrate jazzer.js with novel fuzzing engines

### ISSUE THREAD

**Issue by jasikpark** [CodeIntelligenceTesting/jazzer.js#117]
Thanks for working on this project! I'm glad to see something like `js-fuzz` that is more actively developed 👍 

I'm currently exploring using this to fuzz `prettier` formatter parsers, and I was wondering if y'all could provide any insight into how I might make use of https://github.com/googleprojectzero/fuzzilli/blob/main/Docs/HowFuzzilliWorks.md to generate js programs for prettier's `babel` parser to format.

It's pretty extensively used, so I doubt I'll find easy bugs in it but 🤷

**Comment by bertschneider** [comment]
Great that you're trying out Jazzer.js! 

I didn't know Fuzzilli and I'm also not firm in Swift, so there's probably not much support I can provide. If Swift has some kind of C interop you could try to use a native Node.js addon to call Fuzzilli's `CodeGenerators`. 

Otherwise, you probably would need to write your own code generators based on the provided fuzzer input. [@babel/generator](https://babeljs.io/docs/en/babel-generator) already provides nice functionality to turn an AST into code, which should be a good starting point. When doing that you could use the `exploreState` feedback function to help the fuzzer generate different source code to format. As an example you can have a look at the [maze example](https://github.com/CodeIntelligenceTesting/jazzer.js/blob/main/examples/maze/fuzz.js).

**Comment by bertschneider** [comment]
As you added a "thumbs up" to my answer I assume this is resolved for now. If you have other questions, please feel free to reopen or create a new issue.

**Comment by jasikpark** [comment]
yep, sorry for no response!

i have yet to explore this idea as i haven't worked on jasikpark/fuzz-prettier in a moment / getting Fuzzili running normally was taking me a bit to do, trying to figure out how to set up firefox
